/* THIS IS AN AUTOGENERATED FILE. DO NOT MODIFY. */

#include <stdint.h>

const uint8_t TICKER_COUNT = 5;

enum Ticker {
  AMZN = 0,
  GOOG = 1,
  MSFT = 2,
  NFLX = 3,
  NVDA = 4,
};

const char * const getTicker(Ticker ticker);
