/* THIS IS AN AUTOGENERATED FILE. DO NOT MODIFY. */

#include <Arduino.h>

#include "tickers.h"

const char * const getTicker(Ticker ticker) {
  switch (ticker) {
    case AMZN:
      return "AMZN";
    break;
    case GOOG:
      return "GOOG";
    break;
    case MSFT:
      return "MSFT";
    break;
    case NFLX:
      return "NFLX";
    break;
    case NVDA:
      return "NVDA";
    break;
    default:
      return NULL;
  };
}
